# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43604edda651b86062d7dcf6ea4c0916cb06408228197710fdda29c3b7c163c9c1fda3ca5490efcf6e41162c3f9b93b6b339d77a3a777648d3ccf555f0995f80

test:
  secret_key_base: ea34f84202773f999df2a1297e626c0b3750e3c726cec86d2964ebf1251db6c3b741cd922f3e651390da868210cf6b490d47a9aa25e8579660e4c9dacd33cf1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
